import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';

/**
 * Two-tier token build: `tokens/primitives.json` (raw palette/scale values)
 * feed `tokens/semantic.json` (+ `semantic.dark.json` overrides) via
 * Style Dictionary references. One source of truth builds four platform
 * outputs: CSS custom properties, a flat JSON snapshot, Kotlin (Jetpack
 * Compose) objects, and a Swift enum.
 */

const PRIMITIVE_ROOTS = new Set(['color', 'space', 'radius', 'font', 'duration']);

const kebabName = (token) => token.path.join('-').replace(/\./g, '-');
const pascalName = (token) =>
  token.path
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
    .replace(/[^A-Za-z0-9]/g, '');
const camelName = (token) => {
  const p = pascalName(token);
  return p.charAt(0).toLowerCase() + p.slice(1);
};

const isDimension = (token) => token.type === 'dimension';
const isColor = (token) => token.type === 'color';
const isNumber = (token) => token.type === 'number';

// --- transforms -------------------------------------------------------

StyleDictionary.registerTransform({
  name: 'name/kebab-path',
  type: 'name',
  transform: kebabName,
});

StyleDictionary.registerTransform({
  name: 'value/css',
  type: 'value',
  transitive: false,
  filter: isDimension,
  transform: (token) => `${parseFloat(token.value)}px`,
});

StyleDictionary.registerTransform({
  name: 'value/compose-color',
  type: 'value',
  transitive: false,
  filter: isColor,
  transform: (token) => {
    const hex = token.value.replace('#', '').toUpperCase();
    const argb = hex.length === 6 ? `FF${hex}` : hex;
    return `Color(0x${argb})`;
  },
});

StyleDictionary.registerTransform({
  name: 'value/compose-dp',
  type: 'value',
  transitive: false,
  filter: isDimension,
  transform: (token) => `${parseFloat(token.value)}.dp`,
});

StyleDictionary.registerTransform({
  name: 'value/swift-color',
  type: 'value',
  transitive: false,
  filter: isColor,
  transform: (token) => {
    const hex = token.value.replace('#', '');
    const r = parseInt(hex.slice(0, 2), 16) / 255;
    const g = parseInt(hex.slice(2, 4), 16) / 255;
    const b = parseInt(hex.slice(4, 6), 16) / 255;
    return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
  },
});

StyleDictionary.registerTransform({
  name: 'value/swift-cgfloat',
  type: 'value',
  transitive: false,
  filter: isDimension,
  transform: (token) => `CGFloat(${parseFloat(token.value)})`,
});

StyleDictionary.registerTransformGroup({
  name: 'svx/css',
  transforms: ['name/kebab-path', 'value/css'],
});

StyleDictionary.registerTransformGroup({
  name: 'svx/json',
  transforms: ['name/kebab-path'],
});

StyleDictionary.registerTransformGroup({
  name: 'svx/compose',
  transforms: ['name/kebab-path', 'value/compose-color', 'value/compose-dp'],
});

StyleDictionary.registerTransformGroup({
  name: 'svx/swift',
  transforms: ['name/kebab-path', 'value/swift-color', 'value/swift-cgfloat'],
});

// --- formats ------------------------------------------------------------

function cssBlock(tokens, selector) {
  const lines = tokens.map((t) => `  --${kebabName(t)}: ${t.value};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

StyleDictionary.registerFormat({
  name: 'css/svx-variables',
  format: ({ dictionary }) => {
    const primitives = dictionary.allTokens.filter((t) => PRIMITIVE_ROOTS.has(t.path[0]));
    const semantic = dictionary.allTokens.filter((t) => !PRIMITIVE_ROOTS.has(t.path[0]));
    return (
      '/* Auto-generated by @svx/tokens. Do not edit directly. */\n\n' +
      cssBlock(primitives, ':root') +
      '\n' +
      cssBlock(semantic, ':root')
    );
  },
});

StyleDictionary.registerFormat({
  name: 'css/svx-dark-variables',
  format: ({ dictionary }) => {
    const semantic = dictionary.allTokens.filter((t) => !PRIMITIVE_ROOTS.has(t.path[0]));
    return (
      '/* Auto-generated by @svx/tokens. Dark-mode semantic overrides. */\n\n' +
      cssBlock(semantic, "[data-theme='dark']")
    );
  },
});

StyleDictionary.registerFormat({
  name: 'json/svx-nested',
  format: ({ dictionary }) => JSON.stringify(dictionary.tokens, null, 2) + '\n',
});

StyleDictionary.registerFormat({
  name: 'json/svx-flat',
  format: ({ dictionary }) => {
    const out = {};
    for (const t of dictionary.allTokens) {
      out[kebabName(t)] = t.value;
    }
    return JSON.stringify(out, null, 2) + '\n';
  },
});

StyleDictionary.registerFormat({
  name: 'compose/svx-object',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `    val ${camelName(t)} = ${t.value}`);
    return (
      '// Auto-generated by @svx/tokens. Do not edit directly.\n' +
      'package com.svx.tokens\n\n' +
      'import androidx.compose.ui.graphics.Color\n' +
      'import androidx.compose.ui.unit.dp\n\n' +
      'object SvxTokens {\n' +
      lines.join('\n') +
      '\n}\n'
    );
  },
});

StyleDictionary.registerFormat({
  name: 'swift/svx-enum',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((t) => `    static let ${camelName(t)} = ${t.value}`);
    return (
      '// Auto-generated by @svx/tokens. Do not edit directly.\n' +
      'import SwiftUI\n\n' +
      'public enum SvxTokens {\n' +
      lines.join('\n') +
      '\n}\n'
    );
  },
});

// --- build ----------------------------------------------------------------

const light = new StyleDictionary({
  source: ['tokens/primitives.json', 'tokens/semantic.json'],
  platforms: {
    css: {
      transformGroup: 'svx/css',
      buildPath: 'dist/css/',
      files: [{ destination: 'variables.css', format: 'css/svx-variables' }],
    },
    json: {
      transformGroup: 'svx/json',
      buildPath: 'dist/json/',
      files: [
        { destination: 'tokens.json', format: 'json/svx-nested' },
        { destination: 'tokens.flat.json', format: 'json/svx-flat' },
      ],
    },
    compose: {
      transformGroup: 'svx/compose',
      buildPath: 'dist/compose/',
      files: [{ destination: 'SvxTokens.kt', format: 'compose/svx-object' }],
    },
    swift: {
      transformGroup: 'svx/swift',
      buildPath: 'dist/swift/',
      files: [{ destination: 'SvxTokens.swift', format: 'swift/svx-enum' }],
    },
  },
});

const dark = new StyleDictionary({
  source: ['tokens/primitives.json', 'tokens/semantic.json', 'tokens/semantic.dark.json'],
  platforms: {
    css: {
      transformGroup: 'svx/css',
      buildPath: 'dist/css/',
      files: [{ destination: 'variables.dark.css', format: 'css/svx-dark-variables' }],
    },
  },
});

await light.buildAllPlatforms();
await dark.buildAllPlatforms();

// Combine light + dark into a single convenience stylesheet.
const [base, darkOverrides] = await Promise.all([
  fs.readFile('dist/css/variables.css', 'utf8'),
  fs.readFile('dist/css/variables.dark.css', 'utf8'),
]);
await fs.writeFile('dist/css/index.css', `${base}\n${darkOverrides}`);

console.log('Built tokens -> dist/{css,json,compose,swift}');
